version: "3.3"

services: 
  app:
    build: .
    command: nodemon app.js
    ports: 
      - "8080:8080"
    container_name: M7011E_app
    networks:
      - db_network
    depends_on:
      - influx
  influx:
    image: influxdb:latest
    command: 
    container_name: M7011E_influx
    networks:
      - db_network
    enviroment:
      INFLUXDB_ADMIN_USER: node
      INFLUXDB_ADMIN_PASSWORD: node
      INFLUXDB_DB: app_db
  postgress:
    image: postgres:latest
    container_name: M7011E_postgress
    networks:
      - db_network
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: node
      POSTGRES_PASSWORD: node
      POSTGRES_DB: app_db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

networks:
  db_network:
    driver: bridge