version: "3.3"

services: 
  app:
    build: ./app
    command: nodemon app.js
    container_name: M7011E_sim
    ports: 
      - "8080:8080"
    networks: 
      - db_network
    volumes:
      - ./app/code:/home/node/app
    depends_on:
      - db
  db:
    build: ./db
    container_name: M7011E_db2
    ports:
      - "8086:8086"
    networks: 
      - db_network
    hostname: db
    environment:
      INFLUXDB_DB: energy
    volumes:
      - ./db/influxdb-data:/var/lib/mysql
networks: 
  db_network:
    driver: bridge