version: "3.3"

services: 
  sim_app:
    build: ./app
    command: nodemon app.js
    container_name: M7011E_sim_app
    ports: 
      - "8081:8080"
    networks: 
      - sim_network
    volumes:
      - ./app/code:/home/node/app
    depends_on:
      - sim_db
  sim_db:
    build: ./db
    container_name: M7011E_sim_db
    ports:
      - "3306:3306"
    networks: 
      - sim_network
    hostname: sim_db
    environment:
      MYSQL_ROOT_PASSWORD: node
      MYSQL_DATABASE: sim_db
      MYSQL_USER: node
      MYSQL_PASSWORD: node
    volumes:
      - ./db/mariadb-data:/var/lib/mysql
networks: 
  sim_network:
    driver: bridge