version: "3.3"

services: 
  app:
    build: ./app
    command: nodemon app.js
    container_name: M7011E_app
    ports: 
      - "8080:8080"
    volumes:
      - ./code:/home/node/app
  db:
    build: ./db
    container_name: M7011E_db
    ports:
      - "3306":"3306"
    environment:
      MYSQL_ROOT_PASSWORD: node
      MYSQL_DATABASE: web_db
      MYSQL_USER: node
      MYSQL_PASSWORD: node
    volumes:
      - ./mariadb-data:/var/lib/mysql
networks: 
  - ""
