version: "3.3"

services: 
  app:
    build: .
    command: nodemon app.js
    container_name: M7011E_app
    ports: 
      - "8080:8080"
    networks:
      - db_network
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: M7011E_db
    networks: 
      - db_network
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: node
      POSTGRES_PASSWORD: node
      POSTGRES_DB: app_db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

networks:
  db_network:
    driver: bridge