version: "3.3"

services: 
  web_app:
    build: ./app
    command: nodemon app.js
    container_name: M7011E_web_app
    ports: 
      - "8080:8080"
    networks: 
      - web_network
    volumes:
      - ./app/code:/home/node/app
    depends_on:
      - web_db
  web_db:
    build: ./db
    container_name: M7011E_web_db
    ports:
      - "3306:3306"
    networks: 
      - web_network
    hostname: web_db
    environment:
      MYSQL_ROOT_PASSWORD: node
      MYSQL_DATABASE: web_db
      MYSQL_USER: node
      MYSQL_PASSWORD: node
    volumes:
      - ./db/mariadb-data:/var/lib/mysql
networks: 
  web_network:
    driver: bridge
